/**
 * Elitcar arama sonuçlarındaki sıralama (ekonomik grubundan başlar).
 * Listede olmayan araçlar grup önceliğine göre sona eklenir.
 */
export const ELITCAR_ORDER: string[] = [
  // Ekonomik — fiyat sırası (Elitcar ekran görüntüsü)
  "renault-clio-hb",
  "fiat-yeni-egea-sedan",
  "fiat-yeni-egea-hatchback",
  "citroen-c-elysee",
  "fiat-fiorino",
  "fiat-yeni-egea-station-wagon",
  "hyundai-i20",
  "citroen-berlingo",
  "ford-tourneo-courier",
  "renault-symbol",
  "fiat-yeni-egea-cross",
  "renault-megane",
  "fiat-fiorino-panorama",
  "fiat-doblo",
  "fiat-doblo-panorama-dynamic",
  "dacia-sandero-stepway",
  "opel-corsa",
  "volkswagen-polo",
  "toyota-corolla",
  "toyota-corolla-hibrit",
  "ford-focus",
  "honda-city",
  "peugeot-301",
  "citroen-c3",
  "citroen-c4",
  "opel-astra",
  "renault-captur",
  "hyundai-bayon",
  "kia-stonic-cool",
  "dacia-jogger",
  "fiat-panda-urban",
  "fiat-500",
  "fiat-500c",
  "fiat-500-dolcevita",
  "fiat-500l-mirror",
  "fiat-500l-wagon",
  "fiat-500l-cross-plus",
  "opel-combo",
  "volkswagen-caddy",
  "volkswagen-golf",
  "peugeot-408",
  // SUV
  "nissan-juke",
  "opel-crossland",
  "peugeot-2008",
  "citroen-c4x",
  "citroen-c3-aircross",
  "opel-mokka",
  "opel-crossland-x",
  "opel-mokka-x",
  "dacia-duster",
  "renault-austral",
  "renault-captur",
  "peugeot-3008",
  "peugeot-5008",
  "citroen-c5-aircross",
  "nissan-qashqai",
  "hyundai-tucson",
  "kia-sportage",
  "jeep-renegade",
  "mg-zs",
  "fiat-500x-sport",
  "volkswagen-t-cross",
  "volkswagen-taigo",
  "volkswagen-t-roc",
  "volkswagen-tiguan",
  "ds7",
  "chery-tiggo-7",
  "chery-tiggo-8",
  "opel-grandland-x",
  // Minibüs
  "citroen-jumpy-8-1",
  "dacia-lodgy-laureate-7-kisilik",
  "dacia-lodgy-laureate-5",
  "hyundai-staria",
  "mercedes-vito",
  "ford-transit-custom",
  "peugeot-expert-traveller",
  "opel-zafira",
  // Lüks / diğer
  "mercedes-a-200",
  "mercedes-cla-180",
  "mercedes-cla-200-amg",
  "mercedes-c-180",
  "mercedes-c-200",
  "bmw-116d",
  "bmw-320",
  "bmw-520",
  "audi-a6",
  "volkswagen-passat",
  "opel-insignia",
  "opel-vectra",
  "citroen-jumper",
];

export const GROUP_RANK: Record<string, number> = {
  Ekonomik: 0,
  SUV: 1,
  Minibüs: 2,
  Lüks: 3,
};

/** Elitcar listesindeki TL fiyatları (€ × 37) */
export const ELITCAR_PRICES: Record<string, string> = {
  "renault-clio-hb": "1.288 TL",
  "fiat-yeni-egea-sedan": "1.288 TL",
  "fiat-yeni-egea-hatchback": "1.328 TL",
  "citroen-c-elysee": "1.328 TL",
  "fiat-fiorino": "1.336 TL",
  "fiat-yeni-egea-station-wagon": "1.369 TL",
  "hyundai-i20": "1.406 TL",
  "citroen-berlingo": "1.447 TL",
  "ford-tourneo-courier": "1.447 TL",
  "nissan-juke": "1.487 TL",
  "opel-crossland": "1.487 TL",
  "renault-symbol": "1.487 TL",
  "peugeot-2008": "1.628 TL",
  "citroen-c4x": "1.628 TL",
  "citroen-c3-aircross": "1.628 TL",
  "fiat-yeni-egea-cross": "1.691 TL",
  "renault-megane": "1.765 TL",
  "peugeot-3008": "1.939 TL",
};

/** Grup düzeltmeleri (Elitcar kart etiketleri) */
export const GROUP_OVERRIDES: Record<string, string> = {
  "nissan-juke": "SUV",
  "opel-crossland": "SUV",
  "peugeot-2008": "SUV",
  "citroen-c4x": "SUV",
  "citroen-c3-aircross": "SUV",
  "peugeot-3008": "SUV",
  "peugeot-5008": "SUV",
  "citroen-c5-aircross": "SUV",
  "bmw-520": "Lüks",
  "audi-a6": "Lüks",
  "mercedes-cla-200-amg": "Lüks",
  "mercedes-c-200": "Lüks",
};

export const META_OVERRIDES: Record<
  string,
  Partial<{ fuel: string; transmission: string; capacity: string; deposit: string }>
> = {
  "renault-clio-hb": { fuel: "Benzin", transmission: "Manuel", capacity: "5", deposit: "15.540 TL" },
  "fiat-yeni-egea-sedan": { fuel: "Benzin", transmission: "Manuel", capacity: "5", deposit: "15.540 TL" },
  "fiat-yeni-egea-hatchback": { fuel: "Dizel", transmission: "Manuel", capacity: "5", deposit: "15.540 TL" },
  "citroen-c-elysee": { fuel: "Dizel", transmission: "Manuel", capacity: "5", deposit: "15.540 TL" },
  "fiat-fiorino": { fuel: "Dizel", transmission: "Manuel", capacity: "4", deposit: "15.540 TL" },
  "hyundai-i20": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "15.540 TL" },
  "citroen-berlingo": { fuel: "Dizel", transmission: "Otomatik", capacity: "5", deposit: "15.540 TL" },
  "nissan-juke": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "18.500 TL" },
  "opel-crossland": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "18.500 TL" },
  "peugeot-2008": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "18.500 TL" },
  "citroen-c4x": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "18.500 TL" },
  "citroen-c3-aircross": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "18.500 TL" },
  "renault-megane": { fuel: "Benzin", transmission: "Otomatik", capacity: "5", deposit: "18.500 TL" },
};
